apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: face-check
  name: face-check
  namespace: face-check
data:
  ALLOWED_HOSTS: "face-check.w40k.net,*"
  DATABASE_ENGINE: "django.db.backends.postgresql_psycopg2"
  DATABASE_HOST: "w40k.net"
  DATABASE_USER: "face_check"
  DATABASE_NAME: "face_check"
  DATABASE_PORT: "5432"
  DEBUG: "True"

  # SQLITE_DB_LOCATION: "/db/sqlite.db"
  STATIC_ROOT: "/static/"
