apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: face-check
  name: face-check
  namespace: face-check
data:
  ALLOWED_HOSTS: "*"
  SQLITE_DB_LOCATION: "/db/sqlite.db"
  STATIC_ROOT: "/static/"
  MEDIA_ROOT: "/media/"
